In [1]:
import numpy as np
score = np.loadtxt('python_score.csv', delimiter=',', dtype='float64')
score

array([[ 3.,  3.,  4.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  3.,  4.,  4.,  2.,  2.,  4.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  1.,  1.],
       [ 2.,  2.,  3.,  2.,  4.,  2.,  2.,  4.,  4.,  2.,  2.],
       [ 2.,  4.,  2.,  4.,  2.,  2.,  2.,  2.,  4.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  2.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  3.,  4.,  4.,  2.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  2.,  3.,  3.,  3.,  3.,  1.,  3.,  3.,  3.,  3.],
       [ 2.,  2.,  4.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 2.,  2.,  2.,  1.,  1.,  2.,  2

In [2]:
answer = score[:20, -1]
answer

array([3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2., 1.,
       2., 2., 2.])

In [3]:
dset = score[:20, :10].T
dset

array([[3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 4., 1., 1., 2., 4., 1., 4., 4., 2., 3., 3., 3., 2., 2., 2.,
        1., 2., 2., 1.],
       [4., 4., 1., 1., 3., 2., 1., 4., 4., 2., 4., 3., 3., 3., 4., 2.,
        1., 2., 4., 2.],
       [3., 4., 1., 1., 2., 4., 1., 4., 4., 2., 4., 2., 3., 3., 2., 1.,
        1., 2., 2., 4.],
       [3., 4., 1., 1., 4., 2., 1., 4., 4., 2., 2., 3., 3., 3., 2., 1.,
        1., 2., 2., 4.],
       [3., 3., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 4., 1., 1., 2., 2., 1., 4., 4., 2., 4., 3., 3., 1., 2., 2.,
        1., 2., 2., 3.],
       [3., 4., 1., 1., 4., 2., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 2.],
       [3., 2., 1., 2., 4., 4., 1., 4., 4., 2., 4., 3., 3., 3., 2., 2.,
        2., 4., 2., 1.],
       [3., 2., 1., 1., 2., 2., 1., 4., 2., 2., 4., 3., 3., 3., 2., 2.,
        1., 2., 2., 3.]])

In [4]:
bool_dset = (dset == answer)
bool_dset

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True, False,  True,  True, False,  True,  True,  True,  True,
         True, False],
       [False,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True, False,  True,  True,
         True, False],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True, False,  True,  True,  True,  True, False,  True,  True,
         True, False],
       [ True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ T

In [5]:
scoreset1 = bool_dset*1
scoreset1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])

In [6]:
scoreset2 = score[20:,:10].T
scoreset2

array([[ 9.,  5.],
       [ 4.,  7.],
       [10.,  8.],
       [ 9.,  5.],
       [ 6.,  7.],
       [ 8.,  8.],
       [10.,  6.],
       [ 7.,  8.],
       [ 6.,  9.],
       [ 9., 10.]])

In [7]:
distribution1=np.array([4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4]).T

In [8]:
multiple_choice = scoreset1.dot(distribution1)
multiple_choice

array([80, 64, 64, 64, 64, 76, 72, 76, 52, 68])

In [9]:
distribution2 = np.array([1,1])
essay_question= scoreset2.dot(distribution2)
essay_question

array([14., 11., 18., 14., 13., 16., 16., 15., 15., 19.])

In [10]:
total_score= multiple_choice + essay_question
total_score

array([94., 75., 82., 78., 77., 92., 88., 91., 67., 87.])